### ISSUE TITLE
change time system from 12- to 24-hour clock

### ISSUE THREAD

**Issue by roeniss** [antonvs2/gcal-cli#15]
```bash 
$ gcal insert 'interview Mon 11:00'
```

when I typed above, the result was "2020-08-24T23:00:00 ~ 2020-08-25T00:00:00", rather than  "2020-08-24T11:00:00 ~ 2020-08-25T12:00:00" which I thought it would.

can we change this stuff? I think 24-hour time system is more intuitive than 11am or full qualified timestamp (ex, 2020-08-24T11:00:00)

**Comment by toniov** [comment]
Hi!

That's managed by an external module called [Sherlock](https://github.com/neilgupta/Sherlock), I took a look at the documentation, but couldn't find any option to change that behavior. Maybe you could open an issue in that repo.

**Comment by toniov** [comment]
Hi!

That's parsed using an external module called [Sherlock](https://github.com/neilgupta/Sherlock), I took a look at the documentation, but couldn't find any option to change that behavior. Maybe you could open an issue in that repo.

**Comment by roeniss** [comment]
thank you @toniov ! I missed that line in README.md.

**Comment by toniov** [comment]
No prob! Closing this, feel free to open a new issue or write here again for something related to this matter ^^.
